services:
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    volumes:
      - ./:/app
      - server-node-modules:/app/node_modules
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
  server-node-modules:
networks:
  default:
    name: blog_network