services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    # ports:
    #   - 3002:3002
    volumes:
      - ./server:/app
      - server-node-modules:/app/node_modules
  client:
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
    # ports:
    #   - 3000:3000
    volumes:
      - ./client:/app
      - client-node-modules:/app/node_modules
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  nginx:
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
volumes:
  db:
  server-node-modules:
  client-node-modules:
networks:
  default:
    name: chess-network
